  
on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the RSSHub service
      id: RSSHub
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://rss.fatpandac.com"
        expected-statuses: "200,301"
